# Pandas Practice 3
Work through each task in order. Try to solve it yourself before looking anything up!

In [2]:
import pandas as pd
import numpy as np

---
## Level 1 — Basics

### Task 1: Create a DataFrame
Create a DataFrame with 5 rows representing movies.
Columns: `title`, `director`, `year`, `rating` (a float between 1.0 and 10.0), `genre` (use Action, Drama, or Comedy).
Print the DataFrame.

In [3]:
# Your code here
data = {
    'title':    ["Titanic","La La Land","The Brutalist","Moon River", "Red"],   # 5 movie titles
    'director': ["A","B","C","D","E"],   # 5 directors
    'year':     [1990,2010,2025,1990,1980],   # 5 release years
    'rating':   [9.2,8.8,9.3,8.1,8.5],   # 5 ratings (floats)
    'genre':    ["Drama","Drama","Doc","Action","Comedy"],   # 5 genres (Action, Drama, or Comedy)
}

movies = pd.DataFrame(data)
movies

           title director  year  rating   genre
0        Titanic        A  1990     9.2   Drama
1     La La Land        B  2010     8.8   Drama
2  The Brutalist        C  2025     9.3     Doc
3     Moon River        D  1990     8.1  Action
4            Red        E  1980     8.5  Comedy

### Task 2: Inspect a Dataset
Run the cell below to load a dataset, then use `.head()`, `.info()`, `.describe()`, and `.shape` to explore it.

**Question to answer:** How many rows and columns are there? Which columns have missing values?

In [4]:
# Run this to load a sample dataset
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv'
tips = pd.read_csv(url)

# Now explore it — try .head(), .info(), .describe(), .shape below
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [7]:
# Your exploration here
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

### Task 3: Select & Filter
Using your `movies` DataFrame from Task 1:
1. Select only Drama movies
2. Select only movies released after 2000
3. Select just the `title` and `rating` columns

In [11]:
# 1. Filter rows where genre == 'Drama'
dramas = movies[movies['genre'] == 'Drama']
print(dramas)

# 2. Filter rows where year > 2000
recent = movies[movies['year'] > 2000]
print(recent)

# 3. Select just title and rating columns
title_rating = movies[['title','rating']]
print(title_rating)

        title director  year  rating  genre
0     Titanic        A  1990     9.2  Drama
1  La La Land        B  2010     8.8  Drama
           title director  year  rating  genre
1     La La Land        B  2010     8.8  Drama
2  The Brutalist        C  2025     9.3    Doc
           title  rating
0        Titanic     9.2
1     La La Land     8.8
2  The Brutalist     9.3
3     Moon River     8.1
4            Red     8.5

---
## Level 2 — Transformations

### Task 4: Add a Column
Add a column `highly_rated` to your `movies` DataFrame.
It should be `True` if the rating is 8.0 or above, and `False` otherwise.

In [12]:
# Add a 'highly_rated' column
movies['highly_rated'] = movies['rating']>= 8.0
movies

           title director  year  rating   genre  highly_rated
0        Titanic        A  1990     9.2   Drama          True
1     La La Land        B  2010     8.8   Drama          True
2  The Brutalist        C  2025     9.3     Doc          True
3     Moon River        D  1990     8.1  Action          True
4            Red        E  1980     8.5  Comedy          True

### Task 5: Handle Missing Data
A DataFrame with `NaN` values has been created for you.
1. Find which cells are null using `.isnull()`
2. Drop rows with any null values using `.dropna()`
3. Fill null values with the mean of each column using `.fillna()`

In [14]:
# Starter data — don't change this
employees = pd.DataFrame({
    'name':       ['Alice', 'Bob', 'Carol', 'Dave', 'Emma'],
    'salary':     [70000, np.nan, 85000, np.nan, 92000],
    'experience': [3, 5, np.nan, 8, 2],
    'score':      [np.nan, 88, 91, 74, np.nan],
})

# 1. Show which values are null
employees.isnull()

# 2. Drop rows with any null
employees.dropna()

# 3. Fill nulls with the mean of each column
employees.fillna(employees.mean(numeric_only=True))

    name        salary  experience      score
0  Alice  70000.000000         3.0  84.333333
1    Bob  82333.333333         5.0  88.000000
2  Carol  85000.000000         4.5  91.000000
3   Dave  82333.333333         8.0  74.000000
4   Emma  92000.000000         2.0  84.333333

### Task 6: Sort & Rank
A sales DataFrame has been created for you.
1. Sort by `revenue` descending
2. Add a `rank` column (1 = highest revenue) using `.rank()`

In [15]:
# Starter data — don't change this
sales = pd.DataFrame({
    'rep':     ['Alice', 'Bob', 'Carol', 'Dave', 'Emma'],
    'region':  ['North', 'South', 'East', 'West', 'North'],
    'revenue': [42000, 31500, 67800, 55200, 48900],
})

# 1. Sort by revenue descending
sales.sort_values('revenue', ascending=False)

# 2. Add a rank column (1 = highest revenue)
sales['rank'] = sales['revenue'].rank(ascending=False)
sales

     rep region  revenue  rank
0  Alice  North    42000   4.0
1    Bob  South    31500   5.0
2  Carol   East    67800   1.0
3   Dave   West    55200   2.0
4   Emma  North    48900   3.0

---
## Level 3 — Aggregation

### Task 7: GroupBy
Using the `orders` DataFrame below, find the **total revenue per region** using `.groupby()`.

In [16]:
# Starter data — don't change this
orders = pd.DataFrame({
    'region':   ['East', 'West', 'East', 'North', 'West', 'North', 'East'],
    'rep':      ['Alice', 'Bob', 'Carol', 'Dave', 'Alice', 'Bob', 'Dave'],
    'revenue':  [1200, 4500, 800, 3200, 2100, 1750, 950],
})

# Total revenue per region
total_by_region = orders.groupby('region')['revenue'].sum()
total_by_region

region
East     2950
North    4950
West     6600
Name: revenue, dtype: int64

### Task 8: Pivot Table
Using the same `orders` DataFrame, create a pivot table showing the **total revenue** for each combination of `region` and `rep`.

In [17]:
# Create a pivot table
pivot = pd.pivot_table(
    orders,
    values= 'revenue',
    index= 'region',
    columns='rep',
    aggfunc=sum
)
pivot

/var/folders/3r/5sttq01d46zg8zxyw17j5nbw0000gn/T/ipykernel_49125/814573986.py:2: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pivot = pd.pivot_table(

rep      Alice     Bob  Carol    Dave
region
East    1200.0     NaN  800.0   950.0
North      NaN  1750.0    NaN  3200.0
West    2100.0  4500.0    NaN     NaN

### Task 9: Merge DataFrames
Two DataFrames are provided. Merge them on `emp_id` so each row has the employee name and their department.

Try `how='inner'`, `how='left'`, and `how='outer'` — what changes?

In [18]:
# Starter data — don't change this
emp_info = pd.DataFrame({
    'emp_id': [1, 2, 3, 4],
    'name':   ['Alice', 'Bob', 'Carol', 'Dave'],
})

departments = pd.DataFrame({
    'emp_id':     [1, 2, 3, 5],   # note: id 4 is missing, id 5 is extra
    'department': ['Engineering', 'Marketing', 'Engineering', 'HR'],
})

# Merge on emp_id
merged = pd.merge(emp_info, departments, on='emp_id', how='inner')
merged

   emp_id   name   department
0       1  Alice  Engineering
1       2    Bob    Marketing
2       3  Carol  Engineering

---
## Level 4 — Real-world

### Task 10: String Operations
A customer DataFrame has been created for you. Using pandas string methods (`.str`):
1. Convert all `name` values to uppercase
2. Extract the domain from each `email` (everything after the `@`)
3. Filter to only customers whose email is from `gmail.com`

In [28]:
# Starter data — don't change this
customers = pd.DataFrame({
    'name':  ['alice smith', 'bob jones', 'carol white', 'dave brown', 'emma green'],
    'email': ['alice@gmail.com', 'bob@yahoo.com', 'carol@gmail.com', 'dave@outlook.com', 'emma@gmail.com'],
    'age':   [28, 34, 22, 45, 31],
})

# 1. Uppercase names
customers['name'] = customers['name'].str.upper()
customers
# 2. Extract email domain (hint: .str.split('@') or .str.extract())
customers['domain'] = customers['email'].str.split('@').str[1]

# 3. Filter to gmail customers only
gmail_customers = customers[customers['domain'] == "gmail.com"]
gmail_customers

          name            email  age     domain
0  ALICE SMITH  alice@gmail.com   28  gmail.com
2  CAROL WHITE  carol@gmail.com   22  gmail.com
4   EMMA GREEN   emma@gmail.com   31  gmail.com

In [24]:
customers

          name             email  age               domain
0  ALICE SMITH   alice@gmail.com   28   [alice, gmail.com]
1    BOB JONES     bob@yahoo.com   34     [bob, yahoo.com]
2  CAROL WHITE   carol@gmail.com   22   [carol, gmail.com]
3   DAVE BROWN  dave@outlook.com   45  [dave, outlook.com]
4   EMMA GREEN    emma@gmail.com   31    [emma, gmail.com]